apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: paelectionresults-cert
spec:
  commonName: "{{ .Values.fronend.domain }}"
  dnsNames:
  - "{{ .Values.frontend.domain }}"
  - "{{ .Values.backend.pubsub.domain }}"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  secretName: paelectionresults-cert
  subject:
    organizations:
      - {{ .Values.cert.organization }}
  usages:
  - server auth
