apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: 'ghcr.io/sharph/paelectionresults-frontend:{{ .Values.frontend.tag }}'
        name: frontend
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
        env:
        - name: PUBLIC_WS_URL
          value: 'wss://{{ .Values.backend.pubsub.domain }}/ws'
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: frontend
