apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-philly
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ingest-philly
  template:
    metadata:
      labels:
        app: ingest-philly
    spec:
      containers:
      - image: 'ghcr.io/sharph/paelectionresults-backend:{{ .Values.backend.ingest.tag }}'
        name: ingest
        command:
          - python
          - downloader_philly.py
        env:
        - name: REDIS_HOST
          value: "paelectionresults-valkey-primary.paelectionresults.svc.cluster.local"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: MODE
          value: "{{ .Values.backend.ingest.philly.mode }}"
        - name: SYNTHETIC
          value: "{{ .Values.backend.ingest.philly.synthetic }}"
        - name: SLEEP_TIME
          value: "{{ .Values.backend.ingest.philly.sleepTime }}"
        resources:
          limits:
            memory: 512Mi
            cpu: 250m
