apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frontend
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.frontend.domain }}`)
    services:
    - name: frontend
      port: 3000
  tls:
    secretName: paelectionresults-cert
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-redirect
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`{{ .Values.frontend.domain }}`)
    middlewares:
    - name: https-redirect
      namespace: traefik
    services:
    - kind: TraefikService
      name: noop@internal
