valkey:
  auth:
    enabled: false
  architecture: standalone
backend:
  ingest:
    tag: latest
    mode: test
    synthetic: "true"
    sleepTime: "60"
    philly:
      mode: test
      synthetic: "true"
      sleepTime: "60"
  pubsub:
    domain: ''
    tag: latest
frontend:
  domain: ''
  tag: latest
cert:
  organization: ''
