valkey:
  auth:
    enabled: false
  architecture: standalone
backend:
  ingest:
    tag: latest
  pubsub:
    domain: ''
    tag: latest
frontend:
  domain: ''
  tag: latest
cert:
  organization: ''
